# BS4_and_Pandas

In [1]:
import urllib
from bs4 import BeautifulSoup
import pandas as pd

direccion = 'https://www.lmneuquen.com/se-hizo-pasar-dueno-un-terreno-y-lo-vendio-internet-lo-acusaron-estafa-n685827'
codigo = urllib.request.urlopen(direccion)
bea = BeautifulSoup(codigo)
p = bea('p') 

texto = '' 
for x in p:
    if (len(x.attrs)) == 0: 
        a= x.contents[0] 
        texto = str(texto) +  str(a)

almacenar_contar = dict() 
texto = texto.replace(',','').replace('.','').replace(':','').replace('?','').replace('(','').replace(')','') 
letras = texto.lower().split() 
for x in letras:
    if len(x)>3: 
        almacenar_contar[x] = almacenar_contar.get(x,0) + 1 
        


pd.DataFrame(list(almacenar_contar.items()), columns=['palabra', 'contador']).sort_values('contador', ascending=False )

      palabra  contador
0       hecho         2
25      mujer         2
5      hombre         2
29      lugar         2
32       días         2
..        ...       ...
27  acordaron         1
26   contactó         1
24      pesos         1
23     vendía         1
83      sitio         1

[84 rows x 2 columns]